version: 3

tasks:
  default:
    cmds:
      - task: test

  run:
    cmds:
      - ./game.bin
    aliases:
      - r
    method: none
    silent: false
    deps: [compile]

  compile:
    cmds:
      - ./scripts/build_hot_reload.sh
    aliases:
      - c
    method: none
    silent: false
    sources:
      - ./src/*.odin

  test:
    cmds:
      - odin test mania_demo
    aliases:
      - t
    method: none
    silent: true
    sources:
      - ./mania_demo/*.odin
